export interface DocItem {
  title: string;
  url: string;
  icon: string; 
}

export const docs: DocItem[] = [
  { title: "Accessibility", url: "/accessibility", icon: "Accessibility" },
  { title: "Authentication", url: "/authentication", icon: "Lock" },
  { title: "Best Practices", url: "/best-practices", icon: "Lightbulb" },
  { title: "C#", url: "/csharp", icon: "Code2" },
  { title: "CSS3", url: "/css3", icon: "Palette" },
  { title: "Database & ORM", url: "/database-orm", icon: "Database" },
  { title: "Design for Dev", url: "/design-for-developer", icon: "Pen" },
  { title: "DevOps & Deploy", url: "/devops-deployment", icon: "Server" },
  { title: "Email & Notif", url: "/email-notification", icon: "Mail" },
  { title: "Excel", url: "/excel", icon: "Sheet" },
  { title: "Git", url: "/git", icon: "GitBranch" },
  { title: "HTML5", url: "/html5", icon: "Globe" },
  { title: "HTTP", url: "/http", icon: "Link2" },
  { title: "JavaScript", url: "/js", icon: "FileCode" },
  { title: "MathML", url: "/mathml", icon: "Calculator" },
  { title: "Media", url: "/media", icon: "Play" },
  { title: "Next.js App", url: "/nextjs-app-router", icon: "LayoutDashboard" },
  { title: "Next.js Pages", url: "/nextjs-pages-router", icon: "FileText" },
  { title: "Node.js", url: "/nodejs", icon: "Terminal" },
  { title: "Payment", url: "/payment", icon: "CreditCard" },
  { title: "Performance", url: "/performance", icon: "Gauge" },
  { title: "PHP", url: "/php", icon: "Hash" },
  { title: "Privacy", url: "/privacy", icon: "Shield" },
  { title: "PWA", url: "/pwa", icon: "Smartphone" },
  { title: "React.js", url: "/reactjs", icon: "Atom" },
  { title: "Security", url: "/security", icon: "ShieldCheck" },
  { title: "State Management", url: "/state-management", icon: "Layers" },
  { title: "SVG", url: "/svg", icon: "Image" },
  { title: "Tailwind CSS", url: "/tailwind-css", icon: "Wind" },
  { title: "Testing", url: "/testing", icon: "FlaskConical" },
  { title: "TypeScript", url: "/ts", icon: "Braces" },
  { title: "URIs", url: "/uris", icon: "Link2" },
  { title: "Version Control", url: "/version-control", icon: "GitPullRequest" },
  { title: "Web APIs", url: "/web-apis", icon: "Webhook" },
  { title: "WebDriver", url: "/webdriver", icon: "Car" },
  { title: "Word", url: "/word", icon: "FileText" },
  { title: "XML", url: "/xml", icon: "Code2" },
];